version: '3'
services:
  app:
    build: .
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mealmapdb
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mealmapdb