version: '3.8'
services:
  meal-map:
    image: meal-map
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      # 0.0.0.0 to access the server outside the container
      HOST: "0.0.0.0"   
      # host.docker.internal to access host machine from docker container for postgres connection
      DATABASE_URL: "postgresql://postgres:postgres@host.docker.internal:5432/testdb?schema=public"